version: '3.1'

networks:
  api:
    driver: bridge

services:
  db:
    container_name: api_db
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      PGDATA: /data
    volumes:
      - ./data=/data
    # command: postgres -c 'max_connections=5000'
    networks:
      - api

  api:
    container_name: api
    image: docker.io/library/go-grpc-boilerplate:v1
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=api
      - DB_PASS=api
      - DB_NAME=api
      - JWT_SECRET_KEY=jwt-secret-key
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - api
