version: '3.1'

networks:
  infra:
    driver: bridge

services:
  db:
    container_name: infra_db
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data
    volumes:
      - ./data=/data
    # command: postgres -c 'max_connections=5000'
    ports:
      - 5234:5432
    networks:
      - infra

  adminer:
    container_name: infra_adminer
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - infra
