// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: services/grpc/hello/hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloServicesClient is the client API for HelloServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloServicesClient interface {
	SayHello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloResponses, error)
}

type helloServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloServicesClient(cc grpc.ClientConnInterface) HelloServicesClient {
	return &helloServicesClient{cc}
}

func (c *helloServicesClient) SayHello(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloResponses, error) {
	out := new(HelloResponses)
	err := c.cc.Invoke(ctx, "/services.HelloServices/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServicesServer is the server API for HelloServices service.
// All implementations must embed UnimplementedHelloServicesServer
// for forward compatibility
type HelloServicesServer interface {
	SayHello(context.Context, *emptypb.Empty) (*HelloResponses, error)
	mustEmbedUnimplementedHelloServicesServer()
}

// UnimplementedHelloServicesServer must be embedded to have forward compatible implementations.
type UnimplementedHelloServicesServer struct {
}

func (UnimplementedHelloServicesServer) SayHello(context.Context, *emptypb.Empty) (*HelloResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloServicesServer) mustEmbedUnimplementedHelloServicesServer() {}

// UnsafeHelloServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloServicesServer will
// result in compilation errors.
type UnsafeHelloServicesServer interface {
	mustEmbedUnimplementedHelloServicesServer()
}

func RegisterHelloServicesServer(s grpc.ServiceRegistrar, srv HelloServicesServer) {
	s.RegisterService(&HelloServices_ServiceDesc, srv)
}

func _HelloServices_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServicesServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.HelloServices/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServicesServer).SayHello(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloServices_ServiceDesc is the grpc.ServiceDesc for HelloServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.HelloServices",
	HandlerType: (*HelloServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloServices_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/grpc/hello/hello.proto",
}
